import * as stylex from '@stylexjs/stylex';
import './globals.css';

import styles from './layout.style.js';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html {...stylex.props(styles.html)} lang="en">
      <body {...stylex.props(styles.body)}>{children}</body>
    </html>
  );
};

export default RootLayout;
